name: androidTest
on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-cache-${{ runner.os }}-

      - name: Cache AVD
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-cache-${{ runner.os }}-${{ hashFiles('**/*.avd') }}
          restore-keys: avd-cache-${{ runner.os }}-

      - name: Run ktlint Check
        run: ./gradlew ktlintCheck

      - name: Create Android Virtual Device and run all tests
        uses: reactivecircus/android-emulator-runner@v2
        id: testing
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -wipe-data -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            ./gradlew testDebugUnitTest validateDebugScreenshotTest connectedDebugAndroidTest --stacktrace

      - name: Upload Failing Test Report Log
        if: steps.testing.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: app/emulator.log

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: ./app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: ./app/build/reports

